# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
windowrule = opacity .95 override 1, match:initial_title kitty
windowrule = opacity 1 override 1 override, match:title (.*)(- YouTube)(.*)
windowrule = opacity 1 override 1 override,match:class discord

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
	#steam games fullscreen
	name = steam-game-fullscreen
	match:class = (steam_app)(.*)
	opacity = 1 override 1 override
	fullscreen = true
	workspace = special:games
}

windowrule{
	#no anticheat fullscreen
	name = anticheat-float
	match:initial_title = .*EOS_Setup.exe
	fullscreen_state = 0 0
}

windowrule{
	#wofi transparent
	name = wofi-opacity	
	match:class = wofi
	opacity = .85 override .85 override
	stay_focused = true
	pin = true
    border_size = 0
}

windowrule{
    name = steam-launch
    match:title = Launching...
    opacity = .85 override .85 override
}