workspace = 6, monitor:DP-2, layout:scrolling, layoutopt:direction:down
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2

workspace = 1, monitor:DP-1 
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1

workspace = special:games, monitor:DP-1
workspace = special:vm, monitor:DP-1
